name: 'Publish Conda'
description: 'Build and Publish Conda package to Anaconda'
author: 'Vlad Savelyev'

branding:
  icon: 'package'  
  color: 'purple'

inputs:
  subdir:
    description: 'Sub-directory with conda recipe'
    required: true
  anacondatoken:
    description: 'Anaconda access token'
    required: true
  platforms:
    description: 'Platforms to publish [osx/linux/win]'
    default: 'linux osx'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
